"""Add is_active column to user_policy table

Revision ID: 9355aea1526a
Revises: e95057e70bb3
Create Date: 2025-01-19 22:10:06.456507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9355aea1526a'
down_revision = 'e95057e70bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_policy', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_policy', 'is_active')
    # ### end Alembic commands ###
